const data = {
  products: [
    {
      name: 'Evning Dress',
      slug: 'evening-dress',
      description: 'High Quality Dress',
      brand: 'LONDINA',
      category: 'Dresses',
      image: '/images/p1.jpg',
      price: 549,
      ratting: 4.5,
      countInStock: 10,
      numReviews: 10,
    },
    {
      name: 'Elegent Black Bouse',
      slug: 'elegent-black-blouse',
      description: 'High Quality Dress',
      brand: 'LUUD',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 1000,
      ratting: 5,
      countInStock: 15,
      numReviews: 20,
    },
    {
      name: 'Stylish Coat',
      slug: 'styleish-coat',
      description: 'High Quality Dress',
      brand: 'LIINDA',
      category: 'Coats',
      image: '/images/p3.jpg',
      price: 549,
      ratting: 4.5,
      countInStock: 10,
      numReviews: 10,
    },
    {
      name: 'Wide Leg Pants',
      slug: 'wide-leg-pants',
      description: 'High Quality Dress',
      brand: 'MIMOSAS',
      category: 'Dresses',
      image: '/images/p4.jpg',
      price: 549,
      ratting: 3,
      countInStock: 16,
      numReviews: 6,
    },
  ],
};
export default data;
